export class CustomTableViewModel {
  page = 1;
  tableHeadItems: any = {
    category: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Tipo', order: 'category', col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    event: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Categoria', order: null, col: null },
      { name: 'Fecha', order: 'dateTime', col: null },
      { name: 'Sitio', order: 'site', col: null },
      { name: 'Ciudad', order: 'city', col: null },
      { name: 'Pais', order: 'country', col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    scraper: [
      { name: '#', order: '', col: null },
      { name: 'Nombre', order: '', col: null },
      { name: 'Fecha', order: '', col: null },
      { name: 'Sitio', order: '', col: null },
    ],
    site: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Categoria', order: null, col: null },
      { name: 'Ciudad', order: 'city', col: null },
      { name: 'Pais', order: 'country', col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    topSite: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Categoria', order: null, col: null },
      { name: 'Valoracion', order: null, col: null },
      { name: 'Votos', order: null, col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    topEvent: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Categoria', order: null, col: null },
      { name: 'Fecha', order: 'date', col: null },
      { name: 'Valoracion', order: null, col: null },
      { name: 'Votos', order: null, col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    user: [
      { name: 'Nombre', order: '', col: null },
      { name: 'Rol', order: '', col: null },
      { name: 'Email', order: '', col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    voting: [
      { name: 'Tipo', order: 'type', col: 'col-2' },
      { name: 'Valor', order: 'value', col: 'col-4' },
      { name: 'Item', order: null, col: 'col-4' },
      { name: 'Actualizado', order: 'updated', col: 'col-1' },
      { name: 'Creado', order: 'created', col: null },
    ],
  };
}
