export class CustomTableViewModel {
  page = 1;
  tableHeadItems: any = {
    brand: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Pais', order: 'country', col: null },
      { name: 'Continente', order: 'continent', col: null },
      { name: 'Total Coches', order: null, col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    car: [
      { name: '#', order: null, col: null },
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Conductor', order: '', col: null },
      { name: 'Marca', order: '', col: null },
      { name: 'Modelo', order: '', col: null },
      { name: 'Traccion', order: 'traction', col: null },
      { name: 'CC', order: 'cc', col: null },
      { name: 'CV', order: 'cv', col: null },
      { name: 'Año', order: 'year', col: null },
      { name: 'Inscripciones', order: null, col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    inscription: [
      { name: '#', order: null, col: null },
      { name: 'Coche', order: null, col: null },
      { name: 'Torneo', order: null, col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    pairing: [
      { name: 'Coche 1', order: null, col: null },
      { name: 'Coche 2', order: null, col: null },
      { name: 'Votos', order: 'votes1', col: null },
      { name: 'Torneo', order: null, col: null },
      { name: 'Ronda', order: null, col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    tournament: [
      { name: '#', order: '', col: null },
      { name: 'Nombre', order: '', col: null },
      { name: 'Fecha Inicio', order: 'startDate', col: null },
      { name: 'Inscritos', order: '', col: null },
      { name: 'Rondas', order: '', col: null },
      { name: 'Requisitos', order: '', col: null },
      { name: 'Estado', order: 'state', col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    round: [
      { name: 'Nombre', order: 'name', col: null },
      { name: 'Participantes', order: null, col: null },
      { name: 'Torneo', order: 'date', col: null },
      { name: 'Fecha Inicio', order: null, col: null },
      { name: 'Fecha Fin', order: null, col: null },
      { name: 'Estado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    user: [
      { name: 'Nombre', order: '', col: null },
      { name: 'Rol', order: '', col: null },
      { name: 'Email', order: '', col: null },
      { name: 'Coches', order: '', col: null },
      { name: 'Actualizado', order: 'updated', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
    vote: [
      { name: 'Torneo', order: null, col: null },
      { name: 'Ronda', order: null, col: null },
      { name: 'Coche', order: 'value', col: null },
      { name: 'Creado', order: 'created', col: null },
    ],
  };
}
